apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: todos-api
  name: todos-api-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: todos-api
  sessionAffinity: None
  type: LoadBalancer